site_url: https://cookbook.landtiser.family/
logo_url: https://cookbook.landtiser.family/android-chrome-512x512.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'recipes'
    label: 'Recipes'
    label_singular: 'Recipe'
    folder: 'content/recipes'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'recipes/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Content', name: 'body', widget: 'markdown', required: true }
      - label: "Ingredients"
        name: "ingredients"
        collapsed: true
        widget: "list"
        summary: '{{fields.ingredient}} - {{fields.amount.number}} {{fields.amount.unit}}'
        fields:
          - {label: Ingredient, name: ingredient, widget: relation, collection: 'ingredients', search_fields: ['title'], value_field: 'title', display_fields: ['title'] }
          - label: 'Amount'
            name: 'amount'
            widget: 'object'
            summary: '{{fields.number}} {{fields.unit}}'
            fields: 
              - {label: Number, name: number, widget: string }
              - {label: Unit, name: unit, widget: select, options: [whole, teaspoons, tablespoons, ounces, cups, pints, quarts, gallons, pounds, ounces] }
  - name: 'ingredients'
    label: 'Ingredients'
    label_singular: 'Ingredient'
    folder: 'content-ingredients'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    previewpath: 'ingredients/{{slug}}'
    fields:
        - { label: 'Title', name: 'title', widget: 'string', required: true }
        - { label: 'Body', name: 'body', widget: 'markdown', required: false }
